<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2009sp1

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:n="urn:astm-org:CCR" exclude-result-prefixes="xs xsi xsl" xmlns="urn:astm-org:CCR">
	<xsl:namespace-alias stylesheet-prefix="n" result-prefix="#default"/>
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<n:ContinuityOfCareRecord>
			<xsl:attribute name="xsi:schemaLocation">
				<xsl:value-of select="'urn:astm-org:CCR C:/Users/akadapa/Desktop/ADJE2369.3323.xsd'"/>
			</xsl:attribute>
			<xsl:variable name="var1_instance" select="."/>
			<xsl:for-each select="$var1_instance/CCRforDP">
				<n:CCRDocumentObjectID>
					<xsl:value-of select="concat(concat(string(Page1/CCRID), '_'), number(string(Page1/Unique)))"/>
				</n:CCRDocumentObjectID>
			</xsl:for-each>
			<n:Language>
				<n:Text>
					<xsl:value-of select="'&quot;EN&quot;'"/>
				</n:Text>
			</n:Language>
			<n:Version>
				<xsl:value-of select="'&quot;V1.0.&quot;'"/>
			</n:Version>
			<n:DateTime>
				<xsl:for-each select="$var1_instance/CCRforDP">
					<n:ExactDateTime>
						<xsl:value-of select="string(Page1/CurrentDate)"/>
					</n:ExactDateTime>
				</xsl:for-each>
			</n:DateTime>
			<n:Patient>
				<xsl:for-each select="$var1_instance/CCRforDP">
					<n:ActorID>
						<xsl:value-of select="number(string(Page1/Unique))"/>
					</n:ActorID>
				</xsl:for-each>
			</n:Patient>
			<n:From>
				<n:ActorLink>
					<xsl:for-each select="$var1_instance/CCRforDP">
						<n:ActorID>
							<xsl:value-of select="number(string(Page1/Unique))"/>
						</n:ActorID>
					</xsl:for-each>
				</n:ActorLink>
			</n:From>
			<n:Body>
				<n:Problems>
					<xsl:for-each select="$var1_instance/CCRforDP">
						<xsl:variable name="var10_CCRforDP" select="."/>
						<xsl:for-each select="Page1/PhysicianSubform/Physicians">
							<xsl:variable name="var12_Physicians" select="."/>
							<xsl:for-each select="Physician/MedicalProblemSubform/Problems/Problem">
								<n:Problem>
									<n:CCRDataObjectID>
										<xsl:value-of select="number(string(Unique))"/>
									</n:CCRDataObjectID>
									<n:Type>
										<n:Text>
											<xsl:value-of select="'problem'"/>
										</n:Text>
									</n:Type>
									<n:Description>
										<n:Text>
											<xsl:value-of select="number(string(ProblemName))"/>
										</n:Text>
									</n:Description>
									<n:Source>
										<n:Actor>
											<n:ActorID>
												<xsl:value-of select="number(string($var10_CCRforDP/Page1/Unique))"/>
											</n:ActorID>
										</n:Actor>
									</n:Source>
									<n:InternalCCRLink>
										<n:LinkID>
											<xsl:value-of select="number(string($var12_Physicians/Physician/UniqueID))"/>
										</n:LinkID>
										<n:LinkRelationship>
											<xsl:value-of select="'physician'"/>
										</n:LinkRelationship>
									</n:InternalCCRLink>
								</n:Problem>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
				</n:Problems>
				<n:Alerts>
					<xsl:for-each select="$var1_instance/CCRforDP">
						<xsl:variable name="var16_CCRforDP" select="."/>
						<xsl:for-each select="Page1/Alerts/AllergySubform/Allergies/Allergy">
							<n:Alert>
								<n:CCRDataObjectID>
									<xsl:value-of select="number(string(Unique))"/>
								</n:CCRDataObjectID>
								<n:Type>
									<n:Text>
										<xsl:value-of select="string(DropDownList1)"/>
									</n:Text>
								</n:Type>
								<n:Description>
									<n:Text>
										<xsl:value-of select="string(AllergenName)"/>
									</n:Text>
								</n:Description>
								<n:Source>
									<n:Actor>
										<n:ActorID>
											<xsl:value-of select="number(string($var16_CCRforDP/Page1/Unique))"/>
										</n:ActorID>
									</n:Actor>
								</n:Source>
								<n:Reaction>
									<n:Description>
										<n:Text>
											<xsl:value-of select="string(Reaction)"/>
										</n:Text>
									</n:Description>
									<n:Severity>
										<n:Text>
											<xsl:value-of select="string(Severity)"/>
										</n:Text>
									</n:Severity>
								</n:Reaction>
							</n:Alert>
						</xsl:for-each>
					</xsl:for-each>
				</n:Alerts>
				<n:Medications>
					<xsl:for-each select="$var1_instance/CCRforDP">
						<xsl:variable name="var20_CCRforDP" select="."/>
						<xsl:for-each select="Page1/PhysicianSubform/Physicians">
							<xsl:variable name="var22_Physicians" select="."/>
							<xsl:for-each select="Physician/MedicalProblemSubform/Problems/Problem">
								<xsl:variable name="var24_Problem" select="."/>
								<xsl:for-each select="MedicalProblems/MedicationSubform/Medications/Medication">
									<n:Medication>
										<n:CCRDataObjectID>
											<xsl:value-of select="number(string(Unique))"/>
										</n:CCRDataObjectID>
										<n:Type>
											<n:Text>
												<xsl:value-of select="'medication'"/>
											</n:Text>
										</n:Type>
										<n:Description>
											<n:Text>
												<xsl:value-of select="string(MedicatonName)"/>
											</n:Text>
										</n:Description>
										<n:Source>
											<n:Actor>
												<n:ActorID>
													<xsl:value-of select="number(string($var20_CCRforDP/Page1/Unique))"/>
												</n:ActorID>
											</n:Actor>
										</n:Source>
										<n:InternalCCRLink>
											<n:LinkID>
												<xsl:value-of select="number(string($var24_Problem/Unique))"/>
											</n:LinkID>
											<n:LinkRelationship>
												<xsl:value-of select="'problem'"/>
											</n:LinkRelationship>
										</n:InternalCCRLink>
										<n:InternalCCRLink>
											<n:LinkID>
												<xsl:value-of select="number(string($var22_Physicians/Physician/UniqueID))"/>
											</n:LinkID>
											<n:LinkRelationship>
												<xsl:value-of select="'physician'"/>
											</n:LinkRelationship>
										</n:InternalCCRLink>
										<n:Product>
											<n:ProductName>
												<n:Text>
													<xsl:value-of select="'medication'"/>
												</n:Text>
											</n:ProductName>
										</n:Product>
									</n:Medication>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
				</n:Medications>
				<n:MedicalEquipment>
					<xsl:for-each select="$var1_instance/CCRforDP">
						<xsl:variable name="var28_CCRforDP" select="."/>
						<xsl:for-each select="Page1/PhysicianSubform/Physicians">
							<xsl:variable name="var30_Physicians" select="."/>
							<xsl:for-each select="Physician/MedicalProblemSubform/Problems/Problem">
								<xsl:variable name="var32_Problem" select="."/>
								<xsl:for-each select="MedicalProblems/EquipmentSubform/Equipments/Equipment">
									<n:Equipment>
										<n:CCRDataObjectID>
											<xsl:value-of select="number(string(Unique))"/>
										</n:CCRDataObjectID>
										<n:Type>
											<n:Text>
												<xsl:value-of select="string(Type)"/>
											</n:Text>
										</n:Type>
										<n:Description>
											<n:Text>
												<xsl:value-of select="string(EquipmentName)"/>
											</n:Text>
										</n:Description>
										<n:Source>
											<n:Actor>
												<n:ActorID>
													<xsl:value-of select="number(string($var28_CCRforDP/Page1/Unique))"/>
												</n:ActorID>
											</n:Actor>
										</n:Source>
										<n:InternalCCRLink>
											<n:LinkID>
												<xsl:value-of select="number(string($var32_Problem/Unique))"/>
											</n:LinkID>
											<n:LinkRelationship>
												<xsl:value-of select="'problem'"/>
											</n:LinkRelationship>
										</n:InternalCCRLink>
										<n:InternalCCRLink>
											<n:LinkID>
												<xsl:value-of select="number(string($var30_Physicians/Physician/UniqueID))"/>
											</n:LinkID>
											<n:LinkRelationship>
												<xsl:value-of select="'physician'"/>
											</n:LinkRelationship>
										</n:InternalCCRLink>
										<n:Product>
											<n:ProductName>
												<n:Text>
													<xsl:value-of select="string(Type)"/>
												</n:Text>
											</n:ProductName>
										</n:Product>
									</n:Equipment>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
				</n:MedicalEquipment>
				<n:Results>
					<n:Result>
						<xsl:for-each select="$var1_instance/CCRforDP">
							<n:CCRDataObjectID>
								<xsl:value-of select="number(string(Page1/UniqueBG))"/>
							</n:CCRDataObjectID>
						</xsl:for-each>
						<n:Type>
							<n:Text>
								<xsl:value-of select="'hematology'"/>
							</n:Text>
						</n:Type>
						<n:Description>
							<n:Text>
								<xsl:value-of select="'blood group'"/>
							</n:Text>
						</n:Description>
						<n:Source>
							<n:Actor>
								<xsl:for-each select="$var1_instance/CCRforDP">
									<n:ActorID>
										<xsl:value-of select="number(string(Page1/Unique))"/>
									</n:ActorID>
								</xsl:for-each>
							</n:Actor>
						</n:Source>
						<n:Test>
							<xsl:for-each select="$var1_instance/CCRforDP">
								<n:CCRDataObjectID>
									<xsl:value-of select="number(string(Page1/UniqueBG))"/>
								</n:CCRDataObjectID>
							</xsl:for-each>
							<n:Type>
								<n:Text>
									<xsl:value-of select="'hematology'"/>
								</n:Text>
							</n:Type>
							<n:Description>
								<n:Text>
									<xsl:value-of select="'blood group'"/>
								</n:Text>
							</n:Description>
							<n:Source>
								<n:Actor>
									<xsl:for-each select="$var1_instance/CCRforDP">
										<n:ActorID>
											<xsl:value-of select="number(string(Page1/Unique))"/>
										</n:ActorID>
									</xsl:for-each>
								</n:Actor>
							</n:Source>
							<n:TestResult>
								<xsl:for-each select="$var1_instance/CCRforDP">
									<n:Value>
										<xsl:value-of select="string(Page1/Pt_Bloodgroup)"/>
									</n:Value>
								</xsl:for-each>
							</n:TestResult>
						</n:Test>
					</n:Result>
				</n:Results>
				<n:Procedures>
					<xsl:for-each select="$var1_instance/CCRforDP">
						<xsl:variable name="var46_CCRforDP" select="."/>
						<xsl:for-each select="Page1/Alerts/SurgerySubform/Surgeries/Surgery">
							<n:Procedure>
								<n:CCRDataObjectID>
									<xsl:value-of select="number(string(Unique))"/>
								</n:CCRDataObjectID>
								<n:Type>
									<n:Text>
										<xsl:value-of select="string(DropDownList1)"/>
									</n:Text>
								</n:Type>
								<n:Description>
									<n:Text>
										<xsl:value-of select="string(AllergenName)"/>
									</n:Text>
								</n:Description>
								<n:Source>
									<n:Actor>
										<n:ActorID>
											<xsl:value-of select="number(string($var46_CCRforDP/Page1/Unique))"/>
										</n:ActorID>
									</n:Actor>
								</n:Source>
								<n:Indications>
									<n:Indication>
										<n:Description>
											<n:Text>
												<xsl:value-of select="string(Reaction)"/>
											</n:Text>
										</n:Description>
										<n:Source>
											<n:Actor>
												<n:ActorID>
													<xsl:value-of select="number(string($var46_CCRforDP/Page1/Unique))"/>
												</n:ActorID>
											</n:Actor>
										</n:Source>
									</n:Indication>
								</n:Indications>
							</n:Procedure>
						</xsl:for-each>
					</xsl:for-each>
				</n:Procedures>
			</n:Body>
			<n:Actors>
				<n:Actor>
					<xsl:for-each select="$var1_instance/CCRforDP">
						<n:ActorObjectID>
							<xsl:value-of select="number(string(Page1/Unique))"/>
						</n:ActorObjectID>
					</xsl:for-each>
					<n:Person>
						<n:Name>
							<n:CurrentName>
								<xsl:for-each select="$var1_instance/CCRforDP">
									<n:Given>
										<xsl:value-of select="string(Page1/PatientFirstName)"/>
									</n:Given>
								</xsl:for-each>
								<xsl:for-each select="$var1_instance/CCRforDP">
									<n:Middle>
										<xsl:value-of select="string(Page1/PatientMiddleName)"/>
									</n:Middle>
								</xsl:for-each>
								<xsl:for-each select="$var1_instance/CCRforDP">
									<n:Family>
										<xsl:value-of select="string(Page1/PatientLastName)"/>
									</n:Family>
								</xsl:for-each>
							</n:CurrentName>
						</n:Name>
						<n:DateOfBirth>
							<xsl:for-each select="$var1_instance/CCRforDP">
								<n:ExactDateTime>
									<xsl:value-of select="string(Page1/Pt_DOB)"/>
								</n:ExactDateTime>
							</xsl:for-each>
						</n:DateOfBirth>
						<n:Gender>
							<xsl:for-each select="$var1_instance/CCRforDP">
								<n:Text>
									<xsl:value-of select="string(Page1/Pt_Gender)"/>
								</n:Text>
							</xsl:for-each>
						</n:Gender>
					</n:Person>
					<xsl:for-each select="$var1_instance/CCRforDP/Page1/PtPhoneEmail/Phones/Phone">
						<n:Telephone>
							<n:Value>
								<xsl:value-of select="number(string(Phone))"/>
							</n:Value>
							<n:Type>
								<n:Text>
									<xsl:value-of select="string(Type)"/>
								</n:Text>
							</n:Type>
						</n:Telephone>
					</xsl:for-each>
					<xsl:for-each select="$var1_instance/CCRforDP/Page1/PtPhoneEmail/Emails/Email">
						<n:EMail>
							<n:Value>
								<xsl:value-of select="string(EmailID)"/>
							</n:Value>
						</n:EMail>
					</xsl:for-each>
					<n:Source>
						<n:Actor>
							<xsl:for-each select="$var1_instance/CCRforDP">
								<n:ActorID>
									<xsl:value-of select="number(string(Page1/Unique))"/>
								</n:ActorID>
							</xsl:for-each>
						</n:Actor>
					</n:Source>
				</n:Actor>
				<n:Actor>
					<xsl:for-each select="$var1_instance/CCRforDP">
						<n:ActorObjectID>
							<xsl:value-of select="number(string(Page1/UniqueID))"/>
						</n:ActorObjectID>
					</xsl:for-each>
					<n:Person>
						<n:Name>
							<n:CurrentName>
								<xsl:for-each select="$var1_instance/CCRforDP">
									<n:Given>
										<xsl:value-of select="string(Page1/ContactFirstName)"/>
									</n:Given>
								</xsl:for-each>
								<xsl:for-each select="$var1_instance/CCRforDP">
									<n:Middle>
										<xsl:value-of select="string(Page1/ContactMiddleName)"/>
									</n:Middle>
								</xsl:for-each>
								<xsl:for-each select="$var1_instance/CCRforDP">
									<n:Family>
										<xsl:value-of select="string(Page1/ContactLastName)"/>
									</n:Family>
								</xsl:for-each>
							</n:CurrentName>
						</n:Name>
					</n:Person>
					<n:Relation>
						<xsl:for-each select="$var1_instance/CCRforDP">
							<n:Text>
								<xsl:value-of select="string(Page1/Relation)"/>
							</n:Text>
						</xsl:for-each>
					</n:Relation>
					<xsl:for-each select="$var1_instance/CCRforDP/Page1/ContPhoneEmail/Phones/Phone">
						<n:Telephone>
							<n:Value>
								<xsl:value-of select="number(string(Phone))"/>
							</n:Value>
							<n:Type>
								<n:Text>
									<xsl:value-of select="string(Type)"/>
								</n:Text>
							</n:Type>
						</n:Telephone>
					</xsl:for-each>
					<xsl:for-each select="$var1_instance/CCRforDP/Page1/ContPhoneEmail/Emails/Email">
						<n:EMail>
							<n:Value>
								<xsl:value-of select="string(EmailID)"/>
							</n:Value>
						</n:EMail>
					</xsl:for-each>
					<n:Source>
						<n:Actor>
							<xsl:for-each select="$var1_instance/CCRforDP">
								<n:ActorID>
									<xsl:value-of select="number(string(Page1/UniqueID))"/>
								</n:ActorID>
							</xsl:for-each>
						</n:Actor>
					</n:Source>
				</n:Actor>
				<xsl:for-each select="$var1_instance/CCRforDP">
					<xsl:variable name="var84_CCRforDP" select="."/>
					<xsl:for-each select="Page1/PhysicianSubform/Physicians">
						<n:Actor>
							<n:ActorObjectID>
								<xsl:value-of select="number(string(Physician/UniqueID))"/>
							</n:ActorObjectID>
							<n:Person>
								<n:Name>
									<n:CurrentName>
										<n:Given>
											<xsl:value-of select="number(string(Physician/DoctorFirstName))"/>
										</n:Given>
										<n:Middle>
											<xsl:value-of select="string(Physician/DoctorMiddleName)"/>
										</n:Middle>
										<n:Family>
											<xsl:value-of select="string(Physician/DoctorLastName)"/>
										</n:Family>
									</n:CurrentName>
								</n:Name>
							</n:Person>
							<n:Specialty>
								<n:Text>
									<xsl:value-of select="string(Physician/Speciality)"/>
								</n:Text>
							</n:Specialty>
							<n:Address>
								<n:City>
									<xsl:value-of select="string(Physician/City)"/>
								</n:City>
								<n:State>
									<xsl:value-of select="string(Physician/State)"/>
								</n:State>
							</n:Address>
							<n:Source>
								<n:Actor>
									<n:ActorID>
										<xsl:value-of select="number(string($var84_CCRforDP/Page1/Unique))"/>
									</n:ActorID>
								</n:Actor>
							</n:Source>
							<xsl:for-each select="Physician/MedicalProblemSubform/Problems/Problem">
								<n:InternalCCRLink>
									<n:LinkID>
										<xsl:value-of select="number(string(Unique))"/>
									</n:LinkID>
									<n:LinkRelationship>
										<xsl:value-of select="'problem'"/>
									</n:LinkRelationship>
								</n:InternalCCRLink>
							</xsl:for-each>
						</n:Actor>
					</xsl:for-each>
				</xsl:for-each>
			</n:Actors>
		</n:ContinuityOfCareRecord>
	</xsl:template>
</xsl:stylesheet>
